const express = require('express')
const app = express()
const port = 3000
const cors=require('cors')
const bareRoutes=require('./routes/bare')
const albumRoutes=require('./routes/album')
app.use(cors())
app.use(express.json())
app.use('/',bareRoutes)
app.use('/album',albumRoutes)
app.listen(port, () => console.log(`Example app listening on port ${port}!`))