const express = require('express')
const addSong = require('./routes/addSong')
const getSongs=require('./routes/getSongs')
const app = express()
const port = 3000
const cors=require('cors')
const addToPlaylist = require('./routes/addToPlaylist')
const getPlaylist = require('./routes/getPlaylist')
app.use(cors())
app.use(express.json())
app.get('/', (req, res) => res.json('Hello World!'))
app.post('/add',addSong)
app.get('/getSongs',getSongs)
app.post('/addToPlaylist',addToPlaylist)
app.get('/getPlaylist',getPlaylist)
app.listen(port, () => console.log(`Example app listening on port ${port}!`))