const express = require('express')
const addSong = require('./routes/addSong')
const getSongs=require('./routes/getSongs')
const app = express()
const port = 3000
const cors=require('cors')
const addToPlaylist = require('./routes/addToPlaylist')
const getPlaylist = require('./routes/getPlaylist')
const albumData = require('./routes/albumData')
const barData = require('./routes/barData')
const pieData = require('./routes/pieData')
const deleteFromPlaylist = require('./routes/deleteFromPlaylist')
app.use(cors())
app.use(express.json())
app.get('/', (req, res) => res.json(''))
app.post('/add',addSong)
app.get('/getSongs',getSongs)
app.post('/addToPlaylist',addToPlaylist)
app.get('/getPlaylist',getPlaylist)
app.get('/album/:albumname',albumData)
app.delete('/delfromplaylist',deleteFromPlaylist)
app.get('/getbardata',barData)
app.get('/getpiedata',pieData)
app.listen(port, () => console.log(`Example app listening on port ${port}!`))